# Generated by Django 6.0.2 on 2026-04-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testtext_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='correct_keys',
            field=models.JSONField(default=dict),
        ),
    ]
